### PR TITLE
add all 1957 files to repo for preservation

### PR DESCRIPTION
**Pull request by jpkarlsberg**
This pull request uploads all of the files created by digitizing and running OCR on the 1957 minutes book. I'm uploading the entire directory as per @jpkarlsberg and @willf's [instructions](https://github.com/sacred-harp-minutes/sacred-harp-minutes/blob/master/docs/how-to-setup-a-year.md).

### CODE REVIEW

**Comment by willf** [comment]
@jpkarlsberg , should these be in a separate directory based on OCR source? And why `1957/1957` ? should y ou rename the second one as the OCR source?

**Comment by jpkarlsberg** [comment]
@willf: ABBYY OCR is run on the TIFFs during the digitization post-processing, which generates the `OCR` and `ALTO` folders. Then I independently run OCR on the TIFFs using OCRopus, which generates the `1957` folder and `1957.txt` file in a separate directory. My thinking was to minimize the risk of human error by simply moving the `1957` folder and `1957.txt` file into the parent directory for the year but not making any other changes. But I agree that this is confusing.

I could just retitle the `1957` folder something like `OCROPUS` and move the text file into that folder.

Or I could change `OCR` to `OCR-A` and `1957` to `OCR-O`? And maybe also move the `1957.txt` file into the `OCR-O` folder. But this is stuff that I figured I was saving for the repo for correcting the year's minutes.

**Comment by jpkarlsberg** [comment]
Thinking this through further, I do like the idea of retitling the `1957` folder `OCROPUS` and placing the `1957.txt` file within that subdirectory.

@willf: do you agree with that approach? And if so, how do we make this change to what I've uploaded?

**Comment by willf** [comment]
Something like this, starting from the root (and the `preserve-1957` branch):

```bash
> cd 1957
> git mv 1957 OCROPUS
> git mv 1957.txt OCROPUS/1957.txt
> git commit -m 'renaming files'
> git push
```

**Comment by willf** [comment]
Like its bash counterpart `git mv` is how files are renamed, moved, or renamed & move

**Comment by willf** [comment]
I've gone ahead and done this.

**Pull request merged**
